name: PR Validation-SpringBoot 

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
    - main
    paths:
    - 'spring-backend/**'

jobs:
  pr-validation-springboot:
    uses: Dinesh9535/tripbuddies/pipelines/templates/PR-validation/step-build-services.yaml@main
    with: 
      directory: 'springboot'

